### ISSUE TITLE
Licence.md file

### ISSUE THREAD

**Issue by JarrydHuntley** [maurovanetti/inkfungus-template#1]
Would you be able to add a license file to the repository? 

I saw in the demo that the Ink-Funkus Gateway code is licensed as public domain, it'd be nice to have a License.md file to state that.  since that's often what people look for first. 

This method makes it pretty easy: https://stackoverflow.com/a/37895659 . And you could probably add a line that says "Ink and Fungus code is covered on their respective licenses", or something like that.

Thanks and I'm looking forward to diving into this great tool! :)

**Comment by maurovanetti** [comment]
Good advice!
I'm definitely adding the licence, I'm just a bit in doubt about which licence to pick. What do you suggest?

**Comment by JarrydHuntley** [comment]
@maurovanetti Hi, sorry to took me a while to respond. 

I'd personally recommend using the [MIT License](https://github.com/git/git-scm.com/blob/master/MIT-LICENSE.txt). Both Ink and Fungus use that license so it would simplify things by all the code being available under the same license.

I saw you added the GNU General Public License v3.0 to the project, I could be wrong but I think that license requires people to also open source their code after integrating into the project. I think most game developers avoid all GNU GPL code for that reason (I'm not a lawyer so this is just my understanding).

Thanks!

**Comment by JarrydHuntley** [comment]
Hi @maurovanetti ,


(I'm not a lawyer so this doesn't count as legal advice, just my understanding) I did some research and I think because Fungus and Ink use the MIT license I don't think you can use the GPL V3 for your code, since using that would violate the terms of the MIT license for Fungus and Ink.

Also in my research it looks to be the case that if the GPL V3 is used, it does require any game developers that use this code to make their games completely open source. Which would be a big hurdle and why most game developers can't use GPL code.

Let me know if this makes sense or if you have any questions I can try to help! :) 

Thanks! 👍🏿

**Comment by maurovanetti** [comment]
Hi @JarrydHuntley,
 I checked better and I guess you are right.
Using the MIT Licence is just easier because it's consistent with Ink and Fungus and I don't see any reason to restrict the usage of this software to open-source games. I will just quietly replace it, MIT is more lenient therefore it should not be a problem in any case. I was under the impression that the GPL didn't affect applications using this as a library, but your interpretation sounds more convincing. The https://it.wikipedia.org/wiki/GNU_Lesser_General_Public_License would do that but let's keep it simple.
Thank you again.
